### ISSUE TITLE
Problem with Tor 

### ISSUE THREAD

**Issue by steve01101** [MicroRobotProgrammer/TorBridge#8]
Hello, I followed all the steps, but when I try to do "sudo tbcli -r", this comes out.

`wait for restart tor service ..
Job for tor.service failed because the control process exited with error code.
See "systemctl status tor.service" and "journalctl -xeu tor.service" for details.
`

Then I try to type the command: "journalctl -xeu tor.service"

`░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The automatic restart of the tor.service drive has been scheduled, as a result
░░ of the settings configured in Restart=.
gen 04 14:27:46 steve systemd[1]: Stopped Anonymizing overlay network for TCP.
░░ Subject: The tor.service unit has finished shutting down
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The tor.service unit has finished shutting down.
gen 04 14:27:46 steve systemd[1]: tor.service: Start request repeated too quickly.
gen 04 14:27:46 steve systemd[1]: tor.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Tor.service drive entered the 'failed' state with exit-code result.
gen 04 14:27:46 steve systemd[1]: Failed to start Anonymizing overlay network for TCP.
░░ Subject: Tor.service drive failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The tor.service unit failed.
░░ 
░░ The result is failed.`

**Comment by MiniRobotDev** [comment]
what is you'r os ?
i think you'r not configure tor properly
