### ISSUE TITLE
captcha not working

### ISSUE THREAD

**Issue by jstomw** [MicroRobotProgrammer/TorBridge#9]
captcha not accepted on enter
![Screenshot_20230224_133801](https://user-images.githubusercontent.com/126246171/221158357-f3de7986-0070-4e90-882a-2c91d1cb7621.png)

**Comment by MiniRobotDev** [comment]
hi. thanks for reporting this

im from **Iran**. and when i was writing this script i didn't know other people wants to used it

in Iran **https://bridges.torproject.org/bridges** site is filtered. so i have to use **tor bridges** itself to **actually get more bridges**

so what i guess is 

1. **https://bridges.torproject.org/bridges** site changed its method to get bridges
2. **TorBridge** trying to access the site with a broken bridge

sadly tor service is completely inaccessible in my country now. but i can try to fix this anyway

can you provide more information to help me find the problem?

1. where are you from ?
2. output of `grep -i '^name' /etc/os-release|cut -d'"' -f2` ?
3. output of `tbcli -s`
4. can you access **https://bridges.torproject.org/bridges** without VPN or proxy ?
5. do you have any tor bridges in your `/etc/tor/torrc` file ?

and finally sorry for my bad english.

**Comment by MiniRobotDev** [comment]
oops. this scripts so broken... 

i think a rewrite of this script in python would be a good idea

**Comment by MiniRobotDev** [comment]
**good news tor is working in my country!**

i going to write a python version of this. because its helps me too!

**Comment by jstomw** [comment]
> hi. thanks for reporting this
> 
> im from **Iran**. and when i was writing this script i didn't know other people wants to used it
> 
> in Iran **https://bridges.torproject.org/bridges** site is filtered. so i have to use **tor bridges** itself to **actually get more bridges**
> 
> so what i guess is
> 
> 1. **https://bridges.torproject.org/bridges** site changed its method to get bridges
> 2. **TorBridge** trying to access the site with a broken bridge
> 
> sadly tor service is completely inaccessible in my country now. but i can try to fix this anyway
> 
> can you provide more information to help me find the problem?
> 
> 1. where are you from ?
> 2. output of `grep -i '^name' /etc/os-release|cut -d'"' -f2` ?
> 3. output of `tbcli -s`
> 4. can you access **https://bridges.torproject.org/bridges** without VPN or proxy ?
> 5. do you have any tor bridges in your `/etc/tor/torrc` file ?
> 
> and finally sorry for my bad english.

1. RU
2. Ubuntu
3. see attachment:
![Screenshot_20230224_161349](https://user-images.githubusercontent.com/126246171/221187456-cb4ac9be-bdcb-42bc-a626-e6a206598ef7.png)
4. NO
5. YES

**Comment by MiniRobotDev** [comment]
**thank you**. i think its now fixed

try:
`sudo tbcli -U`

**and install updated tbcli**

**NOTE**: you don't have to enter captcha code in uppercase if its `UDXDSA` simply type `udxdsa` 

if you have **others issue** with **tbcli** create **new issue** .

anyway im writing a python version and when its done i upload it in main branch.

**Comment by devshashtag** [comment]
i'm going to close this issue. if you have any problem with tbcli please create new issue

**Comment by devshashtag** [comment]
i'm going to close this issue. if you have any problem with tbcli please create new issue
